### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Underlyingglitch** [End-Tech/syncmatica#32]
When starting the server for the first time with this plugin, the following message is displayed:
```
[11:14:03] [Server thread/ERROR]: Could not load 'plugins/syncmatica-0.2.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:409) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:908) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.Bukkit.reload(Bukkit.java:697) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790) ~[server.jar:3281-Spigot-3892929-eb14700]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:775) ~[server.jar:3281-Spigot-3892929-eb14700]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:475) ~[server.jar:3281-Spigot-3892929-eb14700]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:439) ~[server.jar:3281-Spigot-3892929-eb14700]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[server.jar:3281-Spigot-3892929-eb14700]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[server.jar:3281-Spigot-3892929-eb14700]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[server.jar:3281-Spigot-3892929-eb14700]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 15 more
```

It also hasn't generated any config files

I'm using V0.2.6

**Comment by nnnik** [comment]
Hey this is a fabric mod not a spigot plugin.
Not sure how to write this as a spigot plugin.
