### ISSUE TITLE
Error when joining server on 1.20.6

### ISSUE THREAD

**Issue by Jesper-Hustad** [End-Tech/syncmatica#76]
When I try using the `1.20.2` version I get an error when joining a server running on 1.20.6 without the syncmatica mod.

Is this something that can be easily fixed?
(I know java well, but new to fabric and mc mods)

```java
[17:32:15] [Netty Client IO #2/ERROR]: Mixin apply for mod syncmatica failed syncmatica.mixin.json:MixinCustomPayloadC2SPacket from mod syncmatica -> net.minecraft.class_2817: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on readPayload could not find any targets matching 'Lnet/minecraft/class_2817;method_53026(Lnet/minecraft/class_2960;Lnet/minecraft/class_2540;)Lnet/minecraft/class_8710;' in net.minecraft.class_2817. Using refmap syncmatica-refmap.json [PREINJECT Applicator Phase -> syncmatica.mixin.json:MixinCustomPayloadC2SPacket from mod syncmatica -> Prepare Injections ->  -> handlerdpi$syncmatica$readPayload(Lnet/minecraft/class_2960;Lnet/minecraft/class_2540;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on readPayload could not find any targets matching 'Lnet/minecraft/class_2817;method_53026(Lnet/minecraft/class_2960;Lnet/minecraft/class_2540;)Lnet/minecraft/class_8710;' in net.minecraft.class_2817. Using refmap syncmatica-refmap.json [PREINJECT Applicator Phase -> syncmatica.mixin.json:MixinCustomPayloadC2SPacket from mod syncmatica -> Prepare Injections ->  -> handlerdpi$syncmatica$readPayload(Lnet/minecraft/class_2960;Lnet/minecraft/class_2540;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]

```

**Comment by sakura-ryoko** [comment]
1.20.2 will not work with 1.20.6+

**Comment by sakura-ryoko** [comment]
--> https://github.com/sakura-ryoko/syncmatica/releases
